# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vibration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('process', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vibration.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='safetyAlert',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('safetyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_alert_id', to='Safety.safety')),
            ],
        ),
    ]
