from Root.models import User
from rest_framework import serializers
from Root.serializers.baseserializers import AutoGeneratedSerializer

class UserSerializer(AutoGeneratedSerializer):
    customerId = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = '__all__'

    def get_customerId(self, obj):
        """
        Returns the string representation of the customerId object's id attribute.
        """
        if obj.customerId:
            return str(obj.customerId.id)
        return None