# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PreventiveCheck', '0001_initial'),
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivecheck',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.customer'),
        ),
        migrations.AddField(
            model_name='preventivecheck',
            name='machineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine'),
        ),
        migrations.AddField(
            model_name='preventivecheckalert',
            name='preventiveCheckId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_check_alert_id', to='PreventiveCheck.preventivecheck'),
        ),
    ]
