# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OilAnalysis', '0002_initial'),
        ('Report', '0001_initial'),
        ('Root', '0001_initial'),
        ('Vibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinereport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine'),
        ),
        migrations.AddField(
            model_name='machinereport',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vibration.sensor'),
        ),
        migrations.AddField(
            model_name='imagereport',
            name='machineReportId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.machinereport'),
        ),
        migrations.AddField(
            model_name='oilanalysisreport',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.status'),
        ),
        migrations.AddField(
            model_name='oilanalysisreport',
            name='equipmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OilAnalysis.oilanalysis'),
        ),
    ]
