# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('feedbackDescription', models.TextField()),
                ('priority', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('parentFeedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Feedback.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAlert',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('feedbackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_alert_id', to='Feedback.feedback')),
            ],
        ),
    ]
