# Generated by Django 5.1.8 on 2025-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='parentFeedback',
            new_name='parentFeedbackId',
        ),
    ]
