# Generated by Django 5.1.8 on 2025-05-05 07:28

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('plotType', models.CharField(max_length=255)),
                ('imageURL', models.URLField()),
                ('imageDescription', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Report',
                'verbose_name_plural': 'Image Reports',
            },
        ),
        migrations.CreateModel(
            name='MachineReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OilAnalysisReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('recievedDate', models.DateField(blank=True, null=True)),
                ('reportDate', models.DateField(blank=True, null=True)),
                ('sampleId', models.CharField(max_length=255)),
                ('oaKinematicViscosity40C', models.CharField(blank=True, max_length=255, null=True)),
                ('OaMoistureContent', models.CharField(blank=True, max_length=255, null=True)),
                ('OaKinematicViscosity100C', models.CharField(blank=True, max_length=255, null=True)),
                ('OaTotalAcidNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('OaRecommendations', models.TextField(blank=True, null=True)),
                ('OaAbnormalities', models.TextField(blank=True, null=True)),
                ('fwRubbingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('fwSlidingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('fwCuttingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('fwChunks', models.CharField(blank=True, max_length=255, null=True)),
                ('fwReworked', models.CharField(blank=True, max_length=255, null=True)),
                ('fwSpheres', models.CharField(blank=True, max_length=255, null=True)),
                ('fwDarkMetalloOxides', models.CharField(blank=True, max_length=255, null=True)),
                ('fwRedOxides', models.CharField(blank=True, max_length=255, null=True)),
                ('fwCorrosiveWearDebris', models.CharField(blank=True, max_length=255, null=True)),
                ('fwOtherParameters', models.CharField(blank=True, max_length=255, null=True)),
                ('fwValue', models.CharField(blank=True, max_length=255, null=True)),
                ('fwFerrousDebrisCount', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwRubbingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwSlidingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwCuttingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwGearWear', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwBearingWear', models.CharField(blank=True, max_length=255, null=True)),
                ('nfwWhiteNonFerrousParticles', models.CharField(blank=True, max_length=255, null=True)),
                ('coFrictionPolymers', models.CharField(blank=True, max_length=255, null=True)),
                ('coNonMetallicCrystalline', models.CharField(blank=True, max_length=255, null=True)),
                ('coFibers', models.CharField(blank=True, max_length=255, null=True)),
                ('coOther', models.CharField(blank=True, max_length=255, null=True)),
                ('coWearParticlesImage', models.CharField(blank=True, max_length=255, null=True)),
                ('coImageTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('abnormalities', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('resultDiscussion', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oil Analysis Report',
                'verbose_name_plural': 'Oil Analysis Reports',
            },
        ),
    ]
