# Generated by Django 5.1.8 on 2025-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinereport',
            old_name='machine',
            new_name='machineId',
        ),
        migrations.RenameField(
            model_name='machinereport',
            old_name='sensor',
            new_name='sensorId',
        ),
        migrations.RenameField(
            model_name='oilanalysisreport',
            old_name='condition',
            new_name='statusId',
        ),
    ]
