# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLimits',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Root.alertlimits',),
        ),
        migrations.CreateModel(
            name='LatestData',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('epochTime', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('axis', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bearingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearinglocation')),
            ],
            options={
                'verbose_name': 'Latest Data',
                'verbose_name_plural': 'Latest Data',
            },
        ),
        migrations.CreateModel(
            name='LatestRMSData',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('epochTime', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('axis', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bearingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearinglocation')),
            ],
            options={
                'verbose_name': 'Latest RMS Data',
                'verbose_name_plural': 'Latest RMS Data',
            },
        ),
        migrations.CreateModel(
            name='MultiChannelSensor',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('bearingLocationId', models.JSONField(default=list)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('gRange', models.FloatField(blank=True, null=True)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('configuration', models.BooleanField(blank=True, null=True)),
                ('reportingFrequency', models.FloatField(blank=True, null=True)),
                ('samplingFrequency', models.FloatField(blank=True, null=True)),
                ('numberOfSamples', models.FloatField(blank=True, null=True)),
                ('treshold', models.FloatField(blank=True, null=True)),
                ('csf', models.FloatField(blank=True, null=True)),
                ('postUrl', models.CharField(default='https://dl6a9qlj1b.execute-api.ap-southeast-1.amazonaws.com/PROD/AAMS/MULTI_CHANNEL', max_length=255)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.customer')),
                ('machineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.status')),
                ('technologyParameterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.technology')),
            ],
            options={
                'verbose_name': 'Multi Channel Sensor',
                'verbose_name_plural': 'Multi Channel Sensors',
            },
        ),
        migrations.CreateModel(
            name='ParameterTrend',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('epochTime', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('rawDataPresent', models.BooleanField()),
                ('axis', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bearingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearinglocation')),
            ],
            options={
                'verbose_name': 'Parameter Trend',
                'verbose_name_plural': 'Parameter Trends',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('epochTime', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('axis', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bearingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearinglocation')),
            ],
            options={
                'verbose_name': 'Raw Data',
                'verbose_name_plural': 'Raw Data',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('gRange', models.FloatField(blank=True, null=True)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('configuration', models.BooleanField(blank=True, null=True)),
                ('reportingFrequency', models.IntegerField(blank=True, null=True)),
                ('samplingFrequency', models.IntegerField(blank=True, null=True)),
                ('numberOfSamples', models.IntegerField(blank=True, null=True)),
                ('postUrl', models.URLField(default='https://dl6a9qlj1b.execute-api.ap-southeast-1.amazonaws.com/PROD/online/dataPush')),
                ('tFlag', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bearingLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearinglocation')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.customer')),
                ('machineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine')),
                ('statusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.status')),
                ('technologyParameterId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.technologyparameter')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='vibrationAlert',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('AssetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vib_alert_id', to='Root.machine')),
            ],
        ),
    ]
