# Generated by Django 5.1.8 on 2025-05-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vibration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichannelsensor',
            old_name='treshold',
            new_name='threshold',
        ),
    ]
