# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OilAnalysis', '0001_initial'),
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLimits',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Root.alertlimits',),
        ),
        migrations.AddField(
            model_name='oilanalysis',
            name='machineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine'),
        ),
        migrations.AddField(
            model_name='oilanalysisalert',
            name='AssetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_analysis_alert_id', to='Root.machine'),
        ),
    ]
