# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('machineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine')),
            ],
        ),
        migrations.CreateModel(
            name='spareAlert',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('spareId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_alert_id', to='Spare.spare')),
            ],
        ),
    ]
