# Generated by Django 5.1.8 on 2025-05-05 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Root', '0001_initial'),
        ('Vibration', '0001_initial'),
        ('auth', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sensorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_alert', to='Vibration.sensor'),
        ),
        migrations.AddField(
            model_name='area',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_parentId', to='Root.area'),
        ),
        migrations.AddField(
            model_name='bearinglocation',
            name='bearingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.bearing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_areas', to='Root.area'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subareas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_subareas', to='Root.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='Root.customer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='alertLimitsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.alertlimits'),
        ),
        migrations.AddField(
            model_name='machine',
            name='areaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_area', to='Root.area'),
        ),
        migrations.AddField(
            model_name='machine',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.customer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='subAreaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_sub_area', to='Root.area'),
        ),
        migrations.AddField(
            model_name='bearinglocation',
            name='machineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.machine'),
        ),
        migrations.AddField(
            model_name='alert',
            name='assetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_alert', to='Root.machine'),
        ),
        migrations.AddField(
            model_name='orientation',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.customer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='statusId',
            field=models.ForeignKey(default='65642670e8b6d946f53bf31c', on_delete=django.db.models.deletion.CASCADE, to='Root.status'),
        ),
        migrations.AddField(
            model_name='bearinglocation',
            name='statusId',
            field=models.ForeignKey(default='65642670e8b6d946f53bf31c', on_delete=django.db.models.deletion.CASCADE, to='Root.status'),
        ),
        migrations.AddField(
            model_name='alert',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_alert', to='Root.status'),
        ),
        migrations.AddField(
            model_name='machine',
            name='technologyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.technology'),
        ),
        migrations.AddField(
            model_name='permission',
            name='contentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permission_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='group',
            name='Permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_group_permissions', to='Root.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='customerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='Root.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='userPermissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='Root.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
