# Generated by Django 5.1.8 on 2025-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bearinglocation',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='bearinglocation',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='machine',
            name='machineId',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
