# Generated by Django 5.1.8 on 2025-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0003_rename_created_at_bearinglocation_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
