# Generated by Django 5.1.8 on 2025-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0004_alter_machine_machineid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
