# Generated by Django 5.1.8 on 2025-05-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0005_alter_machine_machineid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machineId',
        ),
    ]
