# Generated by Django 5.1.8 on 2025-05-22 06:59

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Root', '0006_remove_machine_machineid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultType',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fault Type',
                'verbose_name_plural': 'Fault Types',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='areas',
            new_name='areaId',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='subareas',
            new_name='subareaId',
        ),
        migrations.CreateModel(
            name='MachineHealth',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('bearingLocationArr', models.JSONField(blank=True, null=True)),
                ('healthStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('machineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_health', to='Root.machine')),
            ],
            options={
                'verbose_name': 'Machine Health',
                'verbose_name_plural': 'Machine Healths',
            },
        ),
    ]
