# Generated by Django 5.1.8 on 2025-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='customer',
            new_name='customerId',
        ),
    ]
